CREATE TABLE meal_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    total_calories DOUBLE PRECISION,
    total_carbs DOUBLE PRECISION,
    total_proteins DOUBLE PRECISION,
    total_fats DOUBLE PRECISION,
    profile_id INTEGER,
    category VARCHAR(100) NOT NULL,
    is_current BOOLEAN NOT NULL,
    created_by_nutritionist_user_id INTEGER,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE meal_plan_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20),
    CONSTRAINT uk_meal_plan_type_type UNIQUE (type)
);

CREATE TABLE meal_plan_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL,
    day INTEGER NOT NULL,
    meal_plan_type_id INTEGER NOT NULL,
    meal_plan_id INTEGER NOT NULL,
    CONSTRAINT fk_meal_plan_entry_type FOREIGN KEY (meal_plan_type_id) REFERENCES meal_plan_type (id),
    CONSTRAINT fk_meal_plan_entry_plan FOREIGN KEY (meal_plan_id) REFERENCES meal_plans (id)
);

CREATE TABLE meal_plan_tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag VARCHAR(50) NOT NULL,
    meal_plan_id INTEGER,
    CONSTRAINT fk_meal_plan_tags_plan FOREIGN KEY (meal_plan_id) REFERENCES meal_plans (id)
);
