DO $$
DECLARE
    target_table TEXT;
    meal_type TEXT;
BEGIN
    IF to_regclass('public.meal_plan_types') IS NOT NULL THEN
        target_table := 'meal_plan_types';
    ELSE
        CREATE TABLE IF NOT EXISTS meal_plan_type (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type VARCHAR(20)
        );

        target_table := 'meal_plan_type';
    END IF;

    FOREACH meal_type IN ARRAY ARRAY['Breakfast', 'Lunch', 'Dinner', 'Snack']
    LOOP
        EXECUTE format(
            'INSERT INTO %I (type)
             SELECT %L
             WHERE NOT EXISTS (SELECT 1 FROM %I WHERE type = %L)',
            target_table,
            meal_type,
            target_table,
            meal_type
        );
    END LOOP;
END $$;
